'use strict';

// MESSAGE_TYPE : 0(일반), 1(이미지), 2(동영상 : X), 3(첨부파일 : X), 4(링크), 5(이모티콘), 6(전화번호)
// 0:sys, 1:super, 2:admin, 3:mgr, 4:emp, 7:reader,9:guest
// 0:신규대화인사말,1:배정지연,2:답변지연,3:상담 불가 시간 안내 메시지
module.exports = {
  YES: 'Y',
  NO: 'N',
  COMPANY_CODE_SEOUL: '1',
  COMPANY_CODE_INCHEON: '2',
  ROOM_STATE_READY: 0,
  ROOM_STATE_ING: 1,
  ROOM_STATE_CLOSE: 2,
  MESSAGE_TYPE_NORMAL: 0,
  MESSAGE_TYPE_IMAGE: 1,
  MESSAGE_TYPE_MOVIE: 2,
  MESSAGE_TYPE_ATTACH: 3,
  MESSAGE_TYPE_LINK: 4,
  MESSAGE_TYPE_EMOTICION: 5,
  MESSAGE_TYPE_TEL: 6,
  MEMBER_AUTH_SYS: 0,
  MEMBER_AUTH_SUPER: 1,
  MEMBER_AUTH_ADMIN: 2,
  MEMBER_AUTH_MANAGER: 3,
  MEMBER_AUTH_EMP: 4,
  MEMBER_AUTH_READER: 7,
  MEMBER_AUTH_GUEST: 9,
  AUTO_MESSAGE_TYPE_NEW: 0,
  AUTO_MESSAGE_TYPE_MATCH_DELAY: 1,
  AUTO_MESSAGE_TYPE_REPLY_DELAY: 2,
  AUTO_MESSAGE_TYPE_NOT_TIME: 3
};
